function safeIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_$]/g, '_');
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function toTypeScriptType(type) {
  const primitive = { Text: 'string', String: 'string', Bool: 'boolean', Boolean: 'boolean', Int: 'number', Float: 'number', Number: 'number', Instant: 'string', Json: 'unknown', Patch: 'FrontierPatchOperation[]' };
  if (!type) return 'unknown';
  if (typeof type !== 'string') {
    if (type.kind === 'ref') return `${safeIdentifier(type.name)}${type.args?.length ? `<${type.args.map(toTypeScriptType).join(', ')}>` : ''}`;
    if (type.kind === 'set') return `ReadonlySet<${toTypeScriptType(type.item)}>`;
    if (type.kind === 'list') return `readonly ${toTypeScriptType(type.item)}[]`;
    if (type.kind === 'map') return `ReadonlyMap<${toTypeScriptType(type.key)}, ${toTypeScriptType(type.value)}>`;
    if (type.kind === 'record') return `{ ${type.fields.map((field) => `${safeIdentifier(field.name)}${field.optional ? '?' : ''}: ${toTypeScriptType(field.type)}`).join('; ')} }`;
    if (type.kind === 'union') return type.variants.map((variant) => {
      const fields = variant.fields?.length ? ` & { ${variant.fields.map((field) => `${safeIdentifier(field.name)}${field.optional ? '?' : ''}: ${toTypeScriptType(field.type)}`).join('; ')} }` : '';
      return `{ kind: ${JSON.stringify(variant.name)} }${fields}`;
    }).join(' | ') || 'never';
    return 'unknown';
  }
  if (primitive[type]) return primitive[type];
  const setMatch = /^Set<(.+)>$/.exec(type);
  if (setMatch) return `ReadonlySet<${toTypeScriptType(setMatch[1].trim())}>`;
  const listMatch = /^(List|MoveList)<(.+)>$/.exec(type);
  if (listMatch) return `readonly ${toTypeScriptType(listMatch[2].trim())}[]`;
  const mapMatch = /^Map<(.+),(.+)>$/.exec(type);
  if (mapMatch) return `ReadonlyMap<${toTypeScriptType(mapMatch[1].trim())}, ${toTypeScriptType(mapMatch[2].trim())}>`;
  if (/^\{.*\}$/.test(type)) return 'Record<string, unknown>';
  return safeIdentifier(type);
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toTypeScriptAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-typescript.';
  const declarations = [];
  if (options.includeRuntimeTypes ?? true) {
    declarations.push({ kind: 'runtimeTypes' });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type') declarations.push(typeNodeToAst(node));
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'lattice') {
      declarations.push({
        kind: 'latticeDescriptor',
        name: `${safeIdentifier(node.name)}Lattice`,
        value: {
          name: node.name,
          carrier: toTypeScriptType(node.carrier),
          laws: node.laws ?? [],
          frontierCrdt: node.frontierCrdt
        },
        sourceRef: sourceRef(node)
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'capability') {
      declarations.push({
        kind: 'capabilityDescriptor',
        name: `${safeIdentifier(node.name)}Capability`,
        value: {
          capability: node.capability,
          category: node.category,
          input: node.input ? toTypeScriptType(node.input) : undefined,
          returns: node.returns ? toTypeScriptType(node.returns) : undefined,
          effects: node.effects ?? [],
          resources: node.resources ?? [],
          adapters: node.adapters ?? [],
          unsupportedTargets: node.unsupportedTargets ?? []
        },
        sourceRef: sourceRef(node)
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity') declarations.push({
      kind: 'interface',
      name: safeIdentifier(node.name),
      fields: node.fields.map((field) => ({ name: safeIdentifier(field.name), type: toTypeScriptType(field.type), optional: false })),
      sourceRef: sourceRef(node, { regionIds: node.fields.map((field) => field.id) })
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'state') declarations.push({
      kind: 'interface',
      name: `${safeIdentifier(node.name)}State`,
      fields: node.collections.map((collection) => ({ name: safeIdentifier(collection.name), type: toTypeScriptType(collection.type), optional: false })),
      sourceRef: sourceRef(node, { regionIds: node.collections.map((collection) => collection.id) })
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'extern') {
      declarations.push({
        kind: 'externFunction',
        name: safeIdentifier(node.name),
        inputType: node.signature?.input ? toTypeScriptType(node.signature.input) : 'unknown',
        returnType: node.signature?.returns ? toTypeScriptType(node.signature.returns) : 'unknown',
        sourceRef: sourceRef(node)
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      declarations.push({
        kind: 'actionFunction',
        name: safeIdentifier(node.name),
        inputType: node.input ? toTypeScriptType(node.input) : 'unknown',
        returnType: node.returns ? toTypeScriptType(node.returns) : 'FrontierPatchOperation[]',
        sourceRef: sourceRef(node)
      });
    }
  }
  return { kind: 'typescript.module', banner, declarations };
}

export function renderTypeScriptAst(ast) {
  return renderTypeScriptAstWithSourceMap(ast).code;
}

export function renderTypeScriptAstWithSourceMap(ast, options = {}) {
  const lines = [];
  const mappings = [];
  const target = normalizeTarget(options);
  const push = (...items) => {
    for (const item of items) lines.push(...String(item).split('\n'));
  };
  push(`// ${ast.banner}`, '');
  ast.declarations.forEach((declaration, index) => {
    const startLine = lines.length + 1;
    const startIndex = lines.length;
    if (declaration.kind === 'runtimeTypes') {
      push('export type FrontierPatchOperation =', "  | { op: 'set'; path: string; value: unknown }", "  | { op: 'remove'; path: string }", "  | { op: 'insert'; path: string; value: unknown }", "  | { op: 'merge'; path: string; value: unknown };", '');
      push('export interface FrontierLatticeDescriptor {', '  readonly name: string;', '  readonly carrier: string;', '  readonly laws: readonly string[];', '  readonly frontierCrdt?: { readonly packageName?: string; readonly exportName: string; readonly lawChecker?: string };', '}', '');
      push('export interface FrontierCapabilityDescriptor {', '  readonly capability: string;', '  readonly category?: string;', '  readonly input?: string;', '  readonly returns?: string;', '  readonly effects: readonly string[];', '  readonly resources: readonly string[];', '  readonly adapters: readonly unknown[];', '  readonly unsupportedTargets: readonly unknown[];', '}', '');
    }
    if (declaration.kind === 'typeAlias') {
      push(`export type ${declaration.name}${declaration.parameters} = ${declaration.type};`, '');
    }
    if (declaration.kind === 'interface') {
      push(`export interface ${declaration.name}${declaration.parameters ?? ''} {`);
      for (const field of declaration.fields) push(`  ${field.name}${field.optional ? '?' : ''}: ${field.type};`);
      push('}', '');
    }
    if (declaration.kind === 'latticeDescriptor') {
      push(`export const ${declaration.name}: FrontierLatticeDescriptor = {`);
      push(`  name: ${JSON.stringify(declaration.value.name)},`);
      push(`  carrier: ${JSON.stringify(declaration.value.carrier)},`);
      push(`  laws: ${JSON.stringify(declaration.value.laws)},`);
      if (declaration.value.frontierCrdt) push(`  frontierCrdt: ${JSON.stringify(declaration.value.frontierCrdt)}`);
      push('};', '');
    }
    if (declaration.kind === 'capabilityDescriptor') {
      push(`export const ${declaration.name}: FrontierCapabilityDescriptor = ${JSON.stringify(declaration.value, null, 2)};`, '');
    }
    if (declaration.kind === 'externFunction') {
      push(`export declare function ${declaration.name}(input: ${declaration.inputType}): ${declaration.returnType};`, '');
    }
    if (declaration.kind === 'actionFunction') {
      push(`export function ${declaration.name}(`, '  state: unknown,', `  input: ${declaration.inputType},`, '  env: Record<string, unknown> = {}', `): ${declaration.returnType} {`, '  void state;', '  void input;', '  void env;', `  return [] as ${declaration.returnType};`, '}', '');
    }
    const generatedSpan = declarationBlockSpan(lines, startIndex, startLine, declaration, target, options.targetPath);
    if (declaration.sourceRef?.semanticNodeId && generatedSpan) {
      mappings.push(definedObject({
        id: `map_${idFragment(declaration.sourceRef.semanticNodeId)}_${index}`,
        semanticNodeId: declaration.sourceRef.semanticNodeId,
        nativeSourceId: options.nativeSourceId,
        semanticSymbolId: options.semanticSymbolIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
        semanticOccurrenceId: options.semanticOccurrenceIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
        sourceSpan: options.sourceSpansBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
        generatedSpan,
        target,
        generatedName: declaration.name,
        evidenceIds: options.evidence?.map((record) => record.id),
        lossIds: options.lossIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
        precision: 'declaration',
        metadata: {
          generatedSpanStrategy: 'typescript-renderer-declaration-block',
          sourceMapImplication: 'Generated span covers the emitted declaration block and is not token exact.',
          semanticIndexImplication: 'Mapping is anchored by semanticNodeId; symbol and occurrence ids are optional caller-provided links.',
          lossAccountingImplication: 'No loss ids are inferred by the printer; caller-provided loss ids are copied when available.',
          mergeReadinessImplication: 'Suitable for declaration-level overlap review, not fine-grained token merge admission.',
          semanticNodeKind: declaration.sourceRef.semanticNodeKind,
          semanticNodeName: declaration.sourceRef.semanticNodeName,
          regionIds: declaration.sourceRef.regionIds
        }
      }));
    }
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return {
    code,
    sourceMap: definedObject({
      kind: 'frontier.lang.sourceMap',
      version: 1,
      id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_typescript`,
      sourcePath: options.sourcePath,
      sourceHash: options.sourceHash,
      target,
      targetPath: options.targetPath,
      targetHash: options.targetHash,
      semanticIndexId: options.semanticIndexId,
      universalAstId: options.universalAstId,
      nativeAstId: options.nativeAstId,
      nativeSourceId: options.nativeSourceId,
      mappings,
      evidence: options.evidence ?? [],
      metadata: {
        generatedSpanStrategy: 'typescript-renderer-declaration-block',
        precision: 'declaration',
        sourceMapImplication: 'Approximate generated spans are emitted as sidecar mappings without rewriting the printer.',
        semanticIndexImplication: 'Semantic index linkage remains optional and can be attached through ids supplied in options.',
        lossAccountingImplication: 'The renderer does not create loss records; existing loss ids can be associated per semantic node.',
        mergeReadinessImplication: 'Declaration-block mappings can guide generated-output review but should not be treated as token-exact source maps.',
        ...(options.metadata ?? {})
      }
    })
  };
}

export function emitTypeScript(document, options = {}) {
  return renderTypeScriptAst(toTypeScriptAst(document, options));
}

export function emitTypeScriptWithSourceMap(document, options = {}) {
  const ast = toTypeScriptAst(document, options);
  const result = renderTypeScriptAstWithSourceMap(ast, {
    sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_typescript`,
    ...options
  });
  return { ...result, ast };
}

function typeNodeToAst(node) {
  const params = node.parameters?.length ? `<${node.parameters.map(safeIdentifier).join(', ')}>` : '';
  if (node.type) {
    return { kind: 'typeAlias', name: safeIdentifier(node.name), parameters: params, type: toTypeScriptType(node.type), sourceRef: sourceRef(node) };
  }
  if (node.variants?.length) {
    return { kind: 'typeAlias', name: safeIdentifier(node.name), parameters: params, type: toTypeScriptType({ kind: 'union', variants: node.variants }), sourceRef: sourceRef(node) };
  }
  return {
    kind: 'interface',
    name: safeIdentifier(node.name),
    parameters: params,
    fields: (node.fields ?? []).map((field) => ({ name: safeIdentifier(field.name), type: toTypeScriptType(field.type), optional: Boolean(field.optional) })),
    sourceRef: sourceRef(node, { regionIds: (node.fields ?? []).map((field) => field.id) })
  };
}

function declarationBlockSpan(lines, startIndex, startLine, declaration, target, targetPath) {
  let endIndex = lines.length - 1;
  while (endIndex >= startIndex && lines[endIndex] === '') endIndex -= 1;
  if (endIndex < startIndex) return undefined;
  return definedObject({
    path: targetPath,
    target,
    targetPath,
    generatedName: declaration.name,
    startLine,
    startColumn: 1,
    endLine: endIndex + 1,
    endColumn: lines[endIndex].length + 1
  });
}

function normalizeTarget(options) {
  return definedObject({
    ...(options.target ?? {}),
    language: options.target?.language ?? 'typescript',
    emitPath: options.target?.emitPath ?? options.targetPath
  });
}

function definedObject(object) {
  return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined));
}

function idFragment(value) {
  return safeIdentifier(String(value ?? 'unknown')).replace(/^_+/, '') || 'unknown';
}
