function safeIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_$]/g, '_');
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function toTypeScriptType(type) {
  const primitive = { Text: 'string', String: 'string', Bool: 'boolean', Boolean: 'boolean', Int: 'number', Float: 'number', Number: 'number', Instant: 'string', Json: 'unknown', Patch: 'FrontierPatchOperation[]' };
  if (primitive[type]) return primitive[type];
  const setMatch = /^Set<(.+)>$/.exec(type);
  if (setMatch) return `ReadonlySet<${toTypeScriptType(setMatch[1].trim())}>`;
  const listMatch = /^(List|MoveList)<(.+)>$/.exec(type);
  if (listMatch) return `readonly ${toTypeScriptType(listMatch[2].trim())}[]`;
  const mapMatch = /^Map<(.+),(.+)>$/.exec(type);
  if (mapMatch) return `ReadonlyMap<${toTypeScriptType(mapMatch[1].trim())}, ${toTypeScriptType(mapMatch[2].trim())}>`;
  if (/^\{.*\}$/.test(type)) return 'Record<string, unknown>';
  return safeIdentifier(type);
}

export function emitTypeScript(document, options = {}) {
  const lines = [];
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-typescript.';
  lines.push(`// ${banner}`, '');
  if (options.includeRuntimeTypes ?? true) {
    lines.push('export type FrontierPatchOperation =', "  | { op: 'set'; path: string; value: unknown }", "  | { op: 'remove'; path: string }", "  | { op: 'insert'; path: string; value: unknown }", "  | { op: 'merge'; path: string; value: unknown };", '');
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity') {
      lines.push(`export interface ${safeIdentifier(node.name)} {`);
      for (const field of node.fields) lines.push(`  ${safeIdentifier(field.name)}: ${toTypeScriptType(field.type)};`);
      lines.push('}', '');
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      const inputType = node.input ? toTypeScriptType(node.input) : 'unknown';
      const returnType = node.returns ? toTypeScriptType(node.returns) : 'FrontierPatchOperation[]';
      lines.push(`export function ${safeIdentifier(node.name)}(`, '  state: unknown,', `  input: ${inputType},`, '  env: Record<string, unknown> = {}', `): ${returnType} {`, '  void state;', '  void input;', '  void env;', `  return [] as ${returnType};`, '}', '');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}
